### ISSUE TITLE
Erase the Counter of results

### ISSUE THREAD

**Issue by Talixme** [mleeneg/SysNetCheatGUI#1]
First really thanks for your work.

Can you erase the counter number of the results?, it takes more time on show that number that the real search.

Thanks.

**Comment by mleeneg** [comment]
> First really thanks for your work.
> 
> Can you erase the counter number of the results?, it takes more time on show that number that the real search.
> 
> Thanks.

So far I don't really know what you are asking? Are asking about the number of results found or the text box that is displaying the addresses found.

**Comment by Talixme** [comment]
Yes, that one.But maybe its not the one the slow down the seachs, maybe is the value from the searchs.
Thanks

**Comment by mleeneg** [comment]
1. The counter above the results I don't believe slows down the app.
2. The textbox that you see in the right hand side shows what sys-netcheat is displaying.
3. The only thing that might be slow is that SysNetCheatGUI converts the display from sys-netcheat into a list that you can select from.
4. New version of sys-netcheat now limits how many address results are displayed to 100 results.

**Comment by Talixme** [comment]
Thanks
